{"uuid": "f22c08a6-0013-42eb-ab78-8ee316a71601", "counter": 171, "stdout": "\u001b[0;31mfatal: [localhost]: FAILED! => {\u001b[0m\r\n\u001b[0;31m    \"msg\": \"The task includes an option with an undefined variable. The error was: {'name': '{{ item.agent_name }}', 'if_list': \\\"{%- for dict in item.if_list -%} {%-  if 'description' in dict -%} { 'type': '{{ dict.type }}' , 'name': '{{ dict.agent_name }}', 'description': 'to_{{ dict.description }}'}, {%- else -%} { 'type': '{{ dict.type }}' , 'name': '{{ dict.agent_name }}' }, {%- endif -%} {%- endfor -%}\\\"}: 'dict object' has no attribute 'type'\\n\\nThe error appears to be in '/data/project/playbooks/step02.yml': line 57, column 5, but may\\nbe elsewhere in the file depending on the exact syntax problem.\\n\\nThe offending line appears to be:\\n\\n\\n  - name: generate bridge data\\n    ^ here\\n\"\u001b[0m\r\n\u001b[0;31m}\u001b[0m", "start_line": 1463, "end_line": 1466, "runner_ident": "bc43d761-3bbd-4158-b42f-a765c5c041e7", "event": "runner_on_failed", "pid": 24, "created": "2023-04-07T08:17:16.276076", "parent_uuid": "0242ac16-0009-69bb-20a5-00000000000c", "event_data": {"playbook": "/data/project/playbooks/step02.yml", "playbook_uuid": "a469acff-7d53-4ebe-b3ec-5c4486031612", "play": "localhost", "play_uuid": "0242ac16-0009-69bb-20a5-000000000008", "play_pattern": "localhost", "task": "generate bridge data", "task_uuid": "0242ac16-0009-69bb-20a5-00000000000c", "task_action": "set_fact", "resolved_action": "ansible.builtin.set_fact", "task_args": "", "task_path": "/data/project/playbooks/step02.yml:57", "host": "localhost", "remote_addr": "localhost", "res": {"msg": "The task includes an option with an undefined variable. The error was: {'name': '{{ item.agent_name }}', 'if_list': \"{%- for dict in item.if_list -%} {%-  if 'description' in dict -%} { 'type': '{{ dict.type }}' , 'name': '{{ dict.agent_name }}', 'description': 'to_{{ dict.description }}'}, {%- else -%} { 'type': '{{ dict.type }}' , 'name': '{{ dict.agent_name }}' }, {%- endif -%} {%- endfor -%}\"}: 'dict object' has no attribute 'type'\n\nThe error appears to be in '/data/project/playbooks/step02.yml': line 57, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  - name: generate bridge data\n    ^ here\n", "_ansible_no_log": false}, "start": "2023-04-07T08:17:16.233536", "end": "2023-04-07T08:17:16.275857", "duration": 0.042321, "ignore_errors": null, "event_loop": null, "uuid": "f22c08a6-0013-42eb-ab78-8ee316a71601"}}